import React, { memo } from 'react'
import encodeUser from '../utils/encodeUser'
import { NextApiResponse, NextApiRequest } from 'next'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Navbar, Banner, LoginPopup, Features } from '../components/index'
import { Box } from '@chakra-ui/react'
import useStore from '../store/store'
import shallow from 'zustand/shallow'

import { useRouter, RouterEvent } from 'next/router'

const Home: NextPage = () => {
  const openPopup = useStore((state) => state.openPopup, shallow)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box w="full" h="100%" pos="relative">
          <Navbar />
          <Banner />
          {openPopup && <LoginPopup />}
          <Features />
        </Box>
      </main>
    </div>
  )
}

export async function getServerSideProps({
  req,
  res,
}: {
  req: NextApiRequest
  res: NextApiResponse
}) {
  const user = await encodeUser(req)

  res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=59'
  )

  if (user) {
    return {
      redirect: {
        destination: '/custom',
        statusCode: 307,
      },
    }
  }

  return {
    props: {
      user,
    },
  }
}

export default Home
