import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Navbar, LoginPopup } from '../src/components/index'
import { usePopupStore } from '../src/store'
import shallow from 'zustand/shallow'
import { IndexLayout } from '../src/components/layout'

export const Home: NextPage = () => {
  const popupDisplay = usePopupStore(
    (state) => state.indexSignInDisplay,
    shallow
  )

  return (
    <IndexLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="index_main">
          <div className="index_nav">
            <Navbar />
          </div>

          {popupDisplay && <LoginPopup />}
        </div>
      </main>
    </IndexLayout>
  )
}

export default Home
